# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9c8e37780dbccc3492fe1c6fc63c9116c21033120baadf8e53f8083445fde05afcf07ed2175fa8811e166c02356321575d58e51c9746d0c0147adca3cb15582

test:
  secret_key_base: f5d3916225fcc7916aa1fcce3840d92cf1036b9e3740681d3c76b46c5f5e453abdd5a22d13020dd81f78582f3b12ffa244dc05291aff70e08906ae8e3d9ca5e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
